final color FARBE_RECHTS = 0xFF6E7A79;
final color FARBE_UNTEN = 0xFF89999D;
final color FARBE_LINKS = 0xFFD0D5D0;
final color FARBE_OBEN = 0xFFA1AAA7;

final float WAHRSCHEINLICHKEIT_RECHTS = 0.4;
final float WAHRSCHEINLICHKEIT_UNTEN = 0.6;
final float WAHRSCHEINLICHKEIT_LINKS = 0.5;
final float WAHRSCHEINLICHKEIT_OBEN = 0.7;
